### ISSUE TITLE
Edge function doesn't deploy when site uses some frameworks

### ISSUE THREAD

**Issue by jasonbarry** [netlify/integration-csp#15]
In the logs, I see the packaging as expected: 

```
9:43:51 AM: Edge Functions bundling                                       
9:43:51 AM: ────────────────────────────────────────────────────────────────
9:43:51 AM: ​
9:43:51 AM: Packaging Edge Functions from netlify/edge-functions directory:
9:43:51 AM:  - __csp-nonce
```

But after the deploy completes, I don't see it the edge function included in the deploy: 

<img width="665" alt="CleanShot 2023-08-24 at 09 45 28@2x" src="https://github.com/netlify/integration-csp/assets/236451/8a25bdd6-de55-4af9-acee-3bc572bc0e9e">

The initial deploys contain the `CSP-RO` response header, but changing `reportOnly` to `false` seems to not bundle the edge function. Changing the `reportOnly` value back to `true` also doesn't seem to fix it -- I tested on a Gatsby site and a Next.js site.

**Comment by estephinson** [comment]
This is interesting 🤔

**Comment by estephinson** [comment]
So the site I tried it on is using a rather outdated version of the runtime
![CleanShot 2023-10-24 at 12 40 11](https://github.com/netlify/integration-csp/assets/7189223/7ea1dfbb-86ff-40e5-b935-4edd84b488b0)

And it worked, but only after I set the path to `/*`. I also only had the edge functions deployed thing turn up maybe ~30 seconds after the build finished, but it always said it included the EFs

**Comment by jasonbarry** [comment]
@estephinson if the config's path for the integration is empty/undefined, it should be set to `/*`, [like in the plugin](https://github.com/netlify/plugin-csp-nonce/blob/main/manifest.yml#L13) -- can we provide that as a default?

**Comment by jasonbarry** [comment]
@estephinson could we change the default value here to be `/*` ?
