### ISSUE TITLE
True/False fields hide when one value is `false` 

### ISSUE THREAD

**Issue by jasonbarry** [netlify/integration-csp#16]
It looks like if one of the values of the Select menus is `false`, that neither of them render -- notice the missing `Report Only` and `Unsafe Eval` options: 

<img width="693" alt="CleanShot 2023-08-24 at 09 51 47@2x" src="https://github.com/netlify/integration-csp/assets/236451/604dd214-9c6e-4de0-b2b3-ae480b8adcb9">

The only way to restore is to disable and re-enable the integration.

**Comment by estephinson** [comment]
Bet this will be a parsing issue

**Comment by estephinson** [comment]
Looks it, will raise a fix

![CleanShot 2023-08-24 at 18 15 26](https://github.com/netlify/integration-csp/assets/7189223/647c4207-f89c-458e-9ae0-e474658d2339)
